default_platform(:android)

platform :android do
  desc "Build and upload to Firebase App Distribution"
  lane :deploy do
    version_code = ENV['VERSION_CODE'] || 1

    gradle(
      task: ':composeApp:assembleDebug',
      properties: {
        "versionCode" => version_code
      }
    )

    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID'],
      android_artifact_path: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
      service_credentials_file: "service-account.json"
    )
  end
end
