default_platform(:android)

platform :android do
  desc "Build and upload to Firebase App Distribution"
  lane :deploy do
    gradle(task: ':composeApp:assembleDebug')

    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID'],
      android_artifact_path: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
      service_credentials_file: "service-account.json"
    )
  end
end
